# Generated by Django 5.2.6 on 2026-02-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='booking',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='booking_guest',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='api.bookingguest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
