# Generated by Django 5.2.6 on 2026-02-04 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_qrcode_booking_alter_qrcode_booking_guest_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='guest',
        ),
        migrations.AddField(
            model_name='billitem',
            name='booking_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_items', to='api.bookingguest'),
        ),
    ]
