# Generated by Django 6.0.3 on 2026-06-23 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('categorydesc', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('driver', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('affiliate', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Scheduled', 'scheduled'), ('Departed', 'departed'), ('Cancelled', 'cancelled'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
