# Generated by Django 6.0.3 on 2026-06-23 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('categorydesc', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('driver', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('affiliate', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('on_trip', 'On Trip'), ('available', 'Available'), ('Maintenance', 'Maintenance')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='transportation',
            name='status',
            field=models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('departed', 'Departed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
