# Generated by Django 6.0.3 on 2026-06-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_vehicle_alter_transportation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='status',
            field=models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Departed', 'Departed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
